#!/usr/bin/env bash

# This script makes using vm easier

# Initialisation
cd ~/vm/


# VARIABLES

os=$(ls -d */ | dmenu -p "Choose a VM")
ram=$(echo -e "500\n 1000\n 1500\n 2000\n 2500\n" | dmenu -p "Select RAM (in M)")
boot=$(echo -e "c (hardrive)\nd (cdrom)" | dmenu | cut -d " " -f 1 )


# BOOT

cd $os
qemu-system-x86_64 -enable-kvm -cpu host -cdrom *.iso -hda *.img -boot $boot -m $ram -display gtk
