#!/usr/bin/env bash

# This script makes using vm easier

cd ~/vm/
OS=$(ls -d */ | dmenu -p "Choose a VM" -fn "googlesans:size=9.1" -nb "#222831" -nf "#bbbbbb" -sb "#F05454" -sf "#222831")

cd $OS
qemu-system-x86_64 -enable-kvm -boot menu=on -cdrom *.iso -hda *.img -m 1240 -display gtk
